name: Release

on:
  push:
    tags: "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Build archive
        run: mvn -B package --file pom.xml -DskipTests
      - name: Release Plugin zip Archive
        uses: softprops/action-gh-release@v1
        with:
          files: target/components/packages/singlestore-singlestore-kafka-connector-*.zip
